-- MySQL Script generated by MySQL Workbench
-- sáb 17 sep 2016 09:02:29 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema emisora
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `emisora` ;

-- -----------------------------------------------------
-- Schema emisora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emisora` DEFAULT CHARACTER SET utf8 ;
USE `emisora` ;

-- -----------------------------------------------------
-- Table `emisora`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emisora`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `emisora`.`CLIENTE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(5) NULL,
  `contrasena` VARCHAR(5) NULL COMMENT '	',
  `nombre_completo` VARCHAR(500) NULL,
  `documento_identificacion` VARCHAR(200) NULL,
  `correo_electronico` VARCHAR(200) NULL,
  `no_telefono` VARCHAR(200) NULL,
  `no_cuenta` VARCHAR(200) NULL,
  `tipo_cuenta` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emisora`.`REMESA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emisora`.`REMESA` ;

CREATE TABLE IF NOT EXISTS `emisora`.`REMESA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(5) NULL,
  `contrasena` VARCHAR(5) NULL,
  `nombre_receptor` VARCHAR(500) NULL,
  `correo_receptor` VARCHAR(200) NULL,
  `dpi_receptor` VARCHAR(200) NULL,
  `monto_us` DOUBLE NULL,
  `estado_remesa` VARCHAR(10) NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_REMESA_CLIENTE_idx` (`cliente` ASC),
  CONSTRAINT `fk_REMESA_CLIENTE`
    FOREIGN KEY (`cliente`)
    REFERENCES `emisora`.`CLIENTE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
